services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./server/.env.example
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=schedoule
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
